/** @file
 * @brief TODO: Brief docstring.
 *
 * TODO: More documentation here
 *
 * Copyright (C) 2025 MPK Software, St.-Petersburg, Russia
 *
 * @author Stepan Orlov <majorsteve@mail.ru>
 */

// Generated by Google Gemini and further edited manually

#pragma once

#include <QObject>
#include <QImage>

#include <optional>

enum class VideoRecorderStatus : uint8_t
{
    Ready,
    Recording,
    Finishing,
};

struct VideoRecorderOptions
{
    int fps{25};

    // Bitrate defaults to 400 kb/s (tune this for quality/size)
    int64_t bit_rate{400'000};

    // preset can be:
    // ultrafast, superfast, veryfast, faster, fast, medium (default),
    // slow, slower, veryslow
    std::optional<std::string> h264_preset;

    // Note: quality takes precedence over bit_rate.
    // Valid range: 0 (lossless) to 51 (worst)
    std::optional<int> h264_quality;
};

class VideoRecorder : public QObject
{
    Q_OBJECT

public:
    explicit VideoRecorder(QObject *parent = nullptr);
    ~VideoRecorder();

    bool start(
        const QString& file_name, int width, int height,
        const VideoRecorderOptions& options);
    void request_stop();
    auto status() const noexcept -> VideoRecorderStatus;

public slots:
    void enqueue_frame(const QImage& frame);

signals:
    void started();
    void finished();
    void error(const QString& message);

private:
    // This is the main encoding loop running in the separate thread
    void run();

    // Helper functions for FFmpeg setup and cleanup
    bool setupFFmpeg(const QString& file_name, int width, int height, int fps);
    void cleanupFFmpeg();
    bool encodeFrame(const QImage& frame);

private:
    struct Impl;
    Impl* impl_;
};
