#pragma once
// Compatibility shim — use mpk/mix/struct_type_macro.hpp directly in new code.
#include "mpk/mix/struct_type_macro.hpp"

#define GCLIB_STRUCT_TYPE_FIELD_OF      MPKMIX_STRUCT_TYPE_FIELD_OF
#define GCLIB_STRUCT_TYPE_FIELD_NAME    MPKMIX_STRUCT_TYPE_FIELD_NAME
#define GCLIB_STRUCT_TYPE_FIELD_TYPE    MPKMIX_STRUCT_TYPE_FIELD_TYPE
#define GCLIB_STRUCT_TYPE_FIELD_TYPE_REF  MPKMIX_STRUCT_TYPE_FIELD_TYPE_REF
#define GCLIB_STRUCT_TYPE_FIELD_TYPE_CREF MPKMIX_STRUCT_TYPE_FIELD_TYPE_CREF
#define GCLIB_STRUCT_TYPE               MPKMIX_STRUCT_TYPE
