# Generated by Google Gemini

# This file is named FindFFMpeg.cmake.
# It uses standard CMake functions to find FFmpeg libraries and creates the FFMpeg::Encoder alias target.

# The required FFmpeg libraries for the VideoRecorder class:
set(FFMPEG_REQUIRED_LIBS
    libavformat
    libavcodec
    libavutil
    libswscale
)

# Define the internal target name
set(FFMPEG_INTERNAL_TARGET "FFMpeg_Encoder")

# 1. Check if the FFMpeg::Encoder target has already been created (for idempotency)
if(TARGET FFMpeg::Encoder)
    return()
endif()

# 2. Use the standard find_package with the PkgConfig module
find_package(PkgConfig QUIET)

# 3. Search for the FFmpeg components
set(FFMPEG_FOUND FALSE)

if(PKG_CONFIG_FOUND)
    message(STATUS "PkgConfig found. Searching for FFmpeg components...")

    set(FFMPEG_LIBRARIES "")
    set(FFMPEG_INCLUDE_DIRS "")
    set(FFMPEG_FOUND TRUE)

    foreach(LIB_NAME IN ITEMS ${FFMPEG_REQUIRED_LIBS})
        # Use standard pkg_check_modules
        pkg_check_modules(PC_${LIB_NAME} QUIET ${LIB_NAME})

        if(PC_${LIB_NAME}_FOUND)
            list(APPEND FFMPEG_LIBRARIES ${PC_${LIB_NAME}_LIBRARIES})
            list(APPEND FFMPEG_INCLUDE_DIRS ${PC_${LIB_NAME}_INCLUDE_DIRS})
        else()
            message(WARNING "Required FFmpeg component ${LIB_NAME} not found.")
            set(FFMPEG_FOUND FALSE)
        endif()
    endforeach()

    list(REMOVE_DUPLICATES FFMPEG_INCLUDE_DIRS)
    list(REMOVE_DUPLICATES FFMPEG_LIBRARIES)
endif()

# 4. Handle success and create the targets
if(FFMPEG_FOUND)
    message(STATUS "All FFmpeg components found successfully.")

    # A. Define the internal, non-namespaced INTERFACE library.
    add_library(${FFMPEG_INTERNAL_TARGET} INTERFACE)

    # B. Set the properties (include directories and links) on the internal target.
    target_include_directories(${FFMPEG_INTERNAL_TARGET} INTERFACE
        ${FFMPEG_INCLUDE_DIRS}
    )

    target_link_libraries(${FFMPEG_INTERNAL_TARGET} INTERFACE
        ${FFMPEG_LIBRARIES}
    )

    # C. Create the standard, namespaced ALIAS target for consumer use.
    add_library(FFMpeg::Encoder ALIAS ${FFMPEG_INTERNAL_TARGET})

else()
    # Handle failure
    message(WARNING "FFmpeg not found. The VideoRecorder component will not compile.")
    set(FFMPEG_FOUND FALSE)

    if(FFMPEG_FIND_REQUIRED)
        message(FATAL_ERROR "Required FFmpeg components could not be found.")
    endif()

endif()
